version: '3'
services:
  db:
    image: postgres:latest
    healthcheck:
      interval: 1s
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"

  web:
    entrypoint: /bin/echo "`web` disabled; use Flask dev server instead (flask run --reload)"
    restart: no

  mainsail:
    image: ghcr.io/mainsail-crew/mainsail
    volumes:
      - ./data/mainsail-config.json:/usr/share/nginx/html/config.json
    ports:
      - "${MAINSAIL_PORT}:80"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 10s
      timeout: 5s
      retries: 3
    restart: unless-stopped

  octoprint:
    image: octoprint/octoprint
    ports:
      - "${OCTOPRINT_PORT}:5000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 10s
      timeout: 5s
      retries: 6
    volumes:
      - octoprint_data:/octoprint
    restart: unless-stopped
    # Webcam support
    # devices:
    #   - "/dev/video0:/dev/video0"

volumes:
  octoprint_data: null
