version: '3'
name: mus-mission-control-staging
services:
  db:
    networks:
      - core-net-staging
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    
  web:
    networks:
      - core-net-staging
      - core-net
    image: registry.nate3d.com/mus/mission-control:latest
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - MAINSAIL_URL=${MAINSAIL_URL}
      - SECRET_KEY=${SECRET_KEY}
    volumes:
      - data:/data
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mus-m-c-web-wip.rule=Host(`mc.wip.nate3d.com`)"
      - "traefik.http.routers.mus-m-c-web-wip.tls=true"
      - "traefik.http.routers.mus-m-c-web-wip.entrypoints=websecure"
      - "traefik.http.routers.mus-m-c-web-wip.tls.certresolver=tlsresolver"

  mainsail:
    networks:
      - core-net-staging
      - core-net
    volumes:
      - ${PWD}/data/mainsail-config.json:/usr/share/nginx/html/config.json
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mus-m-c-mainsail-wip.rule=Host(`mainsail.mc.wip.nate3d.com`)"
      - "traefik.http.routers.mus-m-c-mainsail-wip.tls=true"
      - "traefik.http.routers.mus-m-c-mainsail-wip.entrypoints=websecure"
      - "traefik.http.routers.mus-m-c-mainsail-wip.tls.certresolver=tlsresolver"

networks:
  core-net-staging:
    external: true
  core-net:
    external: true

volumes:
  data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/data
