version: '3'
name: mus-mission-control-staging
services:
  db:
    networks:
      core-net-staging:
        aliases:
          - db-staging

    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    
  web:
    networks:
      - core-net-staging
      - core-net
    image: registry.nate3d.com/mus/mission-control:latest
    environment:
      - DATABASE_DOMAIN=${DATABASE_DOMAIN}
      - MAINSAIL_DOMAIN=${MAINSAIL_DOMAIN}
      - OCTOPRINT_DOMAIN=${OCTOPRINT_DOMAIN}
      - SQLALCHEMY_DATABASE_URI=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${DATABASE_DOMAIN}/${POSTGRES_DB}
      - WEB_DOMAIN=${WEB_DOMAIN}
      - SECRET_KEY=${SECRET_KEY}
    volumes:
      - data:/data
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mus-m-c-web-wip.rule=Host(`${WEB_DOMAIN}`)"
      - "traefik.http.routers.mus-m-c-web-wip.tls=true"
      - "traefik.http.routers.mus-m-c-web-wip.entrypoints=websecure"
      - "traefik.http.routers.mus-m-c-web-wip.tls.certresolver=tlsresolver"

  mainsail:
    networks:
      - core-net-staging
      - core-net
    environment:
      - MAINSAIL_DOMAIN=${MAINSAIL_DOMAIN}
    volumes:
      - ${PWD}/data/mainsail-config.json:/usr/share/nginx/html/config.json
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mus-m-c-mainsail-wip.rule=Host(`${MAINSAIL_DOMAIN}`)"
      - "traefik.http.routers.mus-m-c-mainsail-wip.tls=true"
      - "traefik.http.routers.mus-m-c-mainsail-wip.entrypoints=websecure"
      - "traefik.http.routers.mus-m-c-mainsail-wip.tls.certresolver=tlsresolver"

  octoprint:
    networks:
      - core-net-staging
      - core-net
    environment:
      - OCTOPRINT_DOMAIN=${OCTOPRINT_DOMAIN}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mus-m-c-octoprint-wip.rule=Host(`${OCTOPRINT_DOMAIN}`)"
      - "traefik.http.routers.mus-m-c-octoprint-wip.tls=true"
      - "traefik.http.routers.mus-m-c-octoprint-wip.entrypoints=websecure"
      - "traefik.http.routers.mus-m-c-octoprint-wip.tls.certresolver=tlsresolver"

networks:
  core-net-staging:
    external: true
  core-net:
    external: true

volumes:
  data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/data
