version: '3'
name: mus-mission-control
services:
  db:
    networks:
      - mus-net
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    
  web:
    networks:
      - mus-net
    build: .
    environment:
      - DATABASE_DOMAIN=${DATABASE_DOMAIN}
      - MAINSAIL_DOMAIN=${MAINSAIL_DOMAIN}
      - OCTOPRINT_DOMAIN=${OCTOPRINT_DOMAIN}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - SQLALCHEMY_DATABASE_URI=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${DATABASE_DOMAIN}/${POSTGRES_DB}
      - WEB_DOMAIN=${WEB_DOMAIN}
      - SECRET_KEY=${SECRET_KEY}
    volumes:
      - data:/data
    restart: no # TODO: REMOVE ME DEBUG ONLY
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mus-m-c-web.rule=Host(`${WEB_DOMAIN}`)"
      - "traefik.http.routers.mus-m-c-web.entrypoints=web"

  mainsail:
    networks:
      - mus-net
    environment:
      - MAINSAIL_DOMAIN=${MAINSAIL_DOMAIN}
    volumes:
      - ${PWD}/data/mainsail-config.json:/usr/share/nginx/html/config.json
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mus-m-c-mainsail.rule=Host(`${MAINSAIL_DOMAIN}`)"
      - "traefik.http.routers.mus-m-c-mainsail.entrypoints=web"

  octoprint:
    networks:
      - mus-net
    environment:
      - OCTOPRINT_DOMAIN=${OCTOPRINT_DOMAIN}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mus-m-c-octoprint.rule=Host(`${OCTOPRINT_DOMAIN}`)"
      - "traefik.http.routers.mus-m-c-octoprint.entrypoints=web"

  traefik:
    image: traefik:latest
    restart: always
    networks:
      - mus-net
    environment:
      - TRAEFIK_DOMAIN=${TRAEFIK_DOMAIN}
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.network=mus-net"
      - "--providers.file.directory=/etc/traefik/config"
      - "--entrypoints.web.address=:80"
      - "--tracing=false"
    ports:
      - "80:80"
      - "8880:8880"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - letsencrypt:/letsencrypt
      - config:/etc/traefik/config
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=mus-net"
      - "traefik.http.routers.traefik.entrypoints=web"
      - "traefik.http.routers.traefik.rule=Host(`${TRAEFIK_DOMAIN}`)"
      - "traefik.http.routers.traefik.service=api@internal"

volumes:
  letsencrypt: null
  config: null
  data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/data


networks:
  mus-net:
    driver: bridge    
