version: '3'
name: nate-web-staging
services:
  nate-web-db:
    container_name: nate-web-db-staging
    networks:
      - core-net-staging
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    
  nate-web:
    container_name: nate-web-staging
    networks:
      - core-net-staging
      - core-net
    image: registry.nate3d.com/nate3d/nate-web:latest
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - MAINSAIL_URL=${MAINSAIL_URL}
      - SECRET_KEY=${SECRET_KEY}
    volumes:
      - data:/data
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nate-web-wip.rule=Host(`wip.nate3d.com`)"
      - "traefik.http.routers.nate-web-wip.tls=true"
      - "traefik.http.routers.nate-web-wip.entrypoints=websecure"
      - "traefik.http.routers.nate-web-wip.tls.certresolver=tlsresolver"

  nate-web-mainsail:
    container_name: nate-web-mainsail-staging
    networks:
      - core-net-staging
      - core-net
    volumes:
      - ${PWD}/data/mainsail-config.json:/usr/share/nginx/html/config.json
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mainsail-wip.rule=Host(`mainsail.wip.nate3d.com`)"
      - "traefik.http.routers.mainsail-wip.tls=true"
      - "traefik.http.routers.mainsail-wip.entrypoints=websecure"
      - "traefik.http.routers.mainsail-wip.tls.certresolver=tlsresolver"

networks:
  core-net-staging:
    external: true
  core-net:
    external: true

volumes:
  data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/data
