version: '3'
services:
  db:
    image: postgres:latest
    healthcheck:
      interval: 1s
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"

  web:
    entrypoint: /bin/echo "`web` disabled; use Flask dev server instead (flask run --reload)"
    restart: no

  mainsail:
    volumes:
      - ./data/mainsail-config.json:/usr/share/nginx/html/config.json
    ports:
      - "5556:80"

  octoprint:
    ports:
      - "5557:5000"
    # Webcam support
    # devices:
    #   - "/dev/video0:/dev/video0"

